### PR TITLE
Fixed Address byte order

### PR DESCRIPTION
**Pull request by thewhobox**
The byte order for the address was wrong.

Unicast 1.1.7 was parsed as 0.9.17 (or something).
So i guess Multicast is the same (not tested on multicast)

### CODE REVIEW

**Comment by xp-development** [comment]
The GetBytes method of the Unicast class has no local variable named 'bytes'. So I get a compile error.

**Comment by thewhobox** [comment]
Ah yes.
In UnicastAddress:
Array.Reverse(bytes);

belongs in the function "FromByteArray".

**Comment by xp-development** [comment]
The first byte contains area and line informations and the second byte the bus device. So I think this method is correct without Array.Reverse. Do you use the TunnelRequestParser? In line 29 the address bytes are swapped.

**Comment by thewhobox** [comment]
Yes, the lines are the same.
`UnicastAddress.FromByteArray(new[] { responseBytes[9], responseBytes[8] }),`

But i still get the wrong Address without Array.Reverse

**Comment by xp-development** [comment]
I think the problem is solved if you swap the bytes in the TunnelRequestParser.
Replace:
UnicastAddress.FromByteArray(new[] { responseBytes[9], responseBytes[8] }),
with:
UnicastAddress.FromByteArray(new[] { responseBytes[8], responseBytes[9] }),

Please try this. If this works fine for you I will merge your pull request.

**Comment by thewhobox** [comment]
Okay.
I swaped the bytes in TunnelRequestParser and removed Array.Reverse

**Comment by thewhobox** [comment]
Thanks for your help.

**Comment by xp-development** [comment]
A new nuget package is available in few minutes.

**Pull request merged**
